# -*- coding: utf-8 -*-
"""Copy of ML_Emotion_Project_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b4F19UYwzDaoE30WEBLerT-tH7NdHsj2
"""

# Cell 1: Mount Google Drive and change directory to project

from google.colab import drive
drive.mount('/content/drive')

import os

project_path = "/content/drive/MyDrive/MLProject"  # adjust if needed
os.chdir(project_path)

print("Current working directory:", os.getcwd())
print("Files in this folder:")
print(os.listdir("."))

# Cell 2: Imports and display settings

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve
)

import matplotlib.pyplot as plt

pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", 200)

# Cell 3: Load the dataset

file_path = "combined.csv"  # same folder as notebook
df = pd.read_csv(file_path, encoding="latin1")  # latin1 safer for this dataset

print("Shape of dataset:", df.shape)
df.head()

# Cell 4: Info and column names (data understanding)

df.info()

print("\nColumns in the dataset:")
print(df.columns.tolist())

# Cell 5: Define emotion label columns (original multi-label)

label_cols = df.columns[9:]  # columns from index 9 onward are labels

print("Number of emotion label columns:", len(label_cols))
print("Emotion label columns:")
print(list(label_cols))

# Cell 6: Number of active labels per example

label_counts_per_example = df[label_cols].sum(axis=1)

print("Number of active labels per example:")
print(label_counts_per_example.value_counts().sort_index())

# Cell 7: Frequency of each emotion label

label_frequencies = df[label_cols].sum().sort_values(ascending=False)
print("Label frequencies (count of 1s):")
print(label_frequencies)

label_proportions = label_frequencies / len(df)
print("\nLabel proportions:")
print(label_proportions)

# Cell 8: Show sample texts with active labels

def show_examples(n=5, min_labels=1, max_labels=3):
    label_counts = df[label_cols].sum(axis=1)
    mask = (label_counts >= min_labels) & (label_counts <= max_labels)
    sample = df[mask].sample(n, random_state=42)

    for i, row in sample.iterrows():
        active = [lab for lab in label_cols if row[lab] == 1]
        print(f"--- Example index {i} ---")
        print("Text:", row["text"])
        print("Active labels:", active)
        print()

show_examples(n=5, min_labels=1, max_labels=2)

# Cell 9: Define Positive / Negative / Neutral-Mixed label groups

positive_labels = [
    'admiration', 'amusement', 'approval', 'caring', 'desire', 'excitement',
    'gratitude', 'joy', 'love', 'optimism', 'pride', 'relief'
]

negative_labels = [
    'anger', 'annoyance', 'disappointment', 'disapproval', 'disgust',
    'embarrassment', 'fear', 'grief', 'nervousness', 'remorse', 'sadness'
]

neutral_mixed_labels = [
    'confusion', 'curiosity', 'realization', 'surprise', 'neutral'
]

# Sanity check: ensure all labels exist in label_cols
all_sentiment_labels = set(positive_labels + negative_labels + neutral_mixed_labels)
missing = all_sentiment_labels - set(label_cols)
print("Missing labels from dataset (should be empty set):", missing)

# Cell 10: Map multi-label emotions to 3-class sentiment

def map_to_sentiment(row):
    pos_count = row[positive_labels].sum()
    neg_count = row[negative_labels].sum()
    neu_count = row[neutral_mixed_labels].sum()

    if (pos_count > 0) and (neg_count == 0) and (neu_count == 0):
        return "positive"
    elif (neg_count > 0) and (pos_count == 0) and (neu_count == 0):
        return "negative"
    else:
        # neutral-only, or any combination/mix of types -> Neutral / Mixed bucket
        if (pos_count + neg_count + neu_count) == 0:
            return np.nan  # no emotion labels at all
        return "neutral_mixed"

df["sentiment_3"] = df.apply(map_to_sentiment, axis=1)

print(df["sentiment_3"].value_counts(dropna=False))

# Cell 11: Sentiment data prep & class distribution

sentiment_df = df.dropna(subset=["sentiment_3"]).copy()

X_text_sent = sentiment_df["text"].astype(str)
y_sentiment = sentiment_df["sentiment_3"]

print("Sentiment class distribution:")
print(y_sentiment.value_counts())
print("\nSentiment class proportions (%):")
print((y_sentiment.value_counts(normalize=True) * 100).round(2).astype(str) + " %")

# Cell 12: Train-test split + TF-IDF for sentiment

X_train_text_sent, X_test_text_sent, y_train_sent, y_test_sent = train_test_split(
    X_text_sent,
    y_sentiment,
    test_size=0.2,
    random_state=42,
    stratify=y_sentiment     # keeps class proportions same in train and test
)

print("Train size:", len(X_train_text_sent))
print("Test size:", len(X_test_text_sent))

tfidf_sent = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1, 2),
    stop_words="english"
)

X_train_tfidf_sent = tfidf_sent.fit_transform(X_train_text_sent)
X_test_tfidf_sent = tfidf_sent.transform(X_test_text_sent)

X_train_tfidf_sent.shape, X_test_tfidf_sent.shape

# Cell 13: Train Logistic Regression for 3-class sentiment

log_reg_sentiment = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",  # handles class imbalance
    multi_class="multinomial",
    solver="lbfgs"
)

log_reg_sentiment.fit(X_train_tfidf_sent, y_train_sent)

y_pred_sent = log_reg_sentiment.predict(X_test_tfidf_sent)

print("Sentiment Logistic Regression model trained.")

# Cell 14: Evaluation for sentiment (Accuracy, Precision, Recall, F1)

from sklearn.metrics import classification_report

accuracy_sent = accuracy_score(y_test_sent, y_pred_sent)
print(f"Sentiment Accuracy: {accuracy_sent:.4f}\n")

print("Classification report - 3-class Sentiment:")
print(classification_report(y_test_sent, y_pred_sent, digits=4))

# Cell 15: Confusion matrix for 3-class sentiment

from sklearn.metrics import ConfusionMatrixDisplay

class_order_sent = ["positive", "negative", "neutral_mixed"]

cm_sent = confusion_matrix(y_test_sent, y_pred_sent, labels=class_order_sent)

disp_sent = ConfusionMatrixDisplay(confusion_matrix=cm_sent, display_labels=class_order_sent)
disp_sent.plot(xticks_rotation=45)
plt.title("Confusion Matrix - 3-Class Sentiment (Logistic Regression)")
plt.show()

# Cell 16: ROC curves and ROC-AUC for 3-class sentiment

from sklearn.preprocessing import label_binarize

class_names_sent = ["positive", "negative", "neutral_mixed"]

y_test_bin_sent = label_binarize(y_test_sent, classes=class_names_sent)
y_proba_sent = log_reg_sentiment.predict_proba(X_test_tfidf_sent)

roc_auc_macro_sent = roc_auc_score(y_test_bin_sent, y_proba_sent, average="macro", multi_class="ovr")
print(f"Macro ROC-AUC (OVR) - Sentiment: {roc_auc_macro_sent:.4f}")

plt.figure(figsize=(7, 6))
for i, class_name in enumerate(class_names_sent):
    fpr, tpr, _ = roc_curve(y_test_bin_sent[:, i], y_proba_sent[:, i])
    plt.plot(fpr, tpr, label=f"{class_name}")

plt.plot([0, 1], [0, 1], "k--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curves - 3-Class Sentiment (Logistic Regression)")
plt.legend()
plt.show()

# Cell 17: Define High / Medium / Low Trust groups and map

# Trust mapping based on project prompt table:
high_trust_labels = [
    'admiration', 'amusement', 'approval', 'caring', 'gratitude', 'joy', 'love', 'optimism'
]

medium_trust_labels = [
    'curiosity', 'desire', 'excitement', 'realization', 'relief', 'surprise', 'pride', 'neutral'
]

low_trust_labels = [
    'anger', 'annoyance', 'disappointment', 'disapproval', 'disgust',
    'embarrassment', 'fear', 'grief', 'nervousness', 'remorse', 'sadness', 'confusion'
]

all_trust_labels = set(high_trust_labels + medium_trust_labels + low_trust_labels)
missing_trust = all_trust_labels - set(label_cols)
print("Missing trust labels (should be empty set):", missing_trust)

def map_to_trust(row):
    hi = row[high_trust_labels].sum()
    med = row[medium_trust_labels].sum()
    lo = row[low_trust_labels].sum()

    total = hi + med + lo
    if total == 0:
        return np.nan  # no emotions at all

    # tie-breaking order: high > medium > low
    if hi >= med and hi >= lo:
        return "high_trust"
    elif med >= hi and med >= lo:
        return "medium_trust"
    else:
        return "low_trust"

df["trust_3"] = df.apply(map_to_trust, axis=1)

print(df["trust_3"].value_counts(dropna=False))

# Cell 18: Trust data prep and class distribution

trust_df = df.dropna(subset=["trust_3"]).copy()

X_text_trust = trust_df["text"].astype(str)
y_trust = trust_df["trust_3"]

print("Trust class distribution:")
print(y_trust.value_counts())
print("\nTrust class proportions (%):")
print((y_trust.value_counts(normalize=True) * 100).round(2).astype(str) + " %")

# Cell 19: Train-test split + TF-IDF + Logistic Regression for trust

X_train_text_trust, X_test_text_trust, y_train_trust, y_test_trust = train_test_split(
    X_text_trust,
    y_trust,
    test_size=0.2,
    random_state=42,
    stratify=y_trust
)

tfidf_trust = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1, 2),
    stop_words="english"
)

X_train_tfidf_trust = tfidf_trust.fit_transform(X_train_text_trust)
X_test_tfidf_trust = tfidf_trust.transform(X_test_text_trust)

log_reg_trust = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    multi_class="multinomial",
    solver="lbfgs"
)

log_reg_trust.fit(X_train_tfidf_trust, y_train_trust)
y_pred_trust = log_reg_trust.predict(X_test_tfidf_trust)

print("Trust Logistic Regression model trained.")

# Cell 20: Evaluation for trust (Accuracy, Precision, Recall, F1)

accuracy_trust = accuracy_score(y_test_trust, y_pred_trust)
print(f"Trust Accuracy: {accuracy_trust:.4f}\n")

print("Classification report - 3-class Trust:")
print(classification_report(y_test_trust, y_pred_trust, digits=4))

# Cell 21: Confusion matrix and ROC for trust

class_order_trust = ["high_trust", "medium_trust", "low_trust"]

cm_trust = confusion_matrix(y_test_trust, y_pred_trust, labels=class_order_trust)

disp_trust = ConfusionMatrixDisplay(confusion_matrix=cm_trust, display_labels=class_order_trust)
disp_trust.plot(xticks_rotation=45)
plt.title("Confusion Matrix - 3-Class Trust (Logistic Regression)")
plt.show()

# ROC curves
class_names_trust = ["high_trust", "medium_trust", "low_trust"]

y_test_bin_trust = label_binarize(y_test_trust, classes=class_names_trust)
y_proba_trust = log_reg_trust.predict_proba(X_test_tfidf_trust)

roc_auc_macro_trust = roc_auc_score(y_test_bin_trust, y_proba_trust, average="macro", multi_class="ovr")
print(f"Macro ROC-AUC (OVR) - Trust: {roc_auc_macro_trust:.4f}")

plt.figure(figsize=(7, 6))
for i, class_name in enumerate(class_names_trust):
    fpr, tpr, _ = roc_curve(y_test_bin_trust[:, i], y_proba_trust[:, i])
    plt.plot(fpr, tpr, label=f"{class_name}")

plt.plot([0, 1], [0, 1], "k--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curves - 3-Class Trust (Logistic Regression)")
plt.legend()
plt.show()

# Cell 22: Multi-label model for original 27+neutral emotions

# Drop rows where all labels are zero (no emotions)
has_any_label = df[label_cols].sum(axis=1) > 0
multi_df = df[has_any_label].copy()

X_text_multi = multi_df["text"].astype(str)
Y_multi = multi_df[label_cols].astype(int)

X_train_text_multi, X_test_text_multi, Y_train_multi, Y_test_multi = train_test_split(
    X_text_multi,
    Y_multi,
    test_size=0.2,
    random_state=42
)

tfidf_multi = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1, 2),
    stop_words="english"
)

X_train_tfidf_multi = tfidf_multi.fit_transform(X_train_text_multi)
X_test_tfidf_multi = tfidf_multi.transform(X_test_text_multi)

base_lr_multi = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    solver="liblinear"  # good for One-vs-Rest + sparse
)

ovr_lr_multi = OneVsRestClassifier(base_lr_multi)
ovr_lr_multi.fit(X_train_tfidf_multi, Y_train_multi)

Y_pred_multi = ovr_lr_multi.predict(X_test_tfidf_multi)

# Multi-label micro/macro metrics
prec_micro, rec_micro, f1_micro, _ = precision_recall_fscore_support(
    Y_test_multi, Y_pred_multi, average="micro", zero_division=0
)
prec_macro, rec_macro, f1_macro, _ = precision_recall_fscore_support(
    Y_test_multi, Y_pred_multi, average="macro", zero_division=0
)

print("Multi-label metrics (27+neutral emotions) - Logistic Regression OVR:")
print(f"Micro  - Precision: {prec_micro:.3f}, Recall: {rec_micro:.3f}, F1: {f1_micro:.3f}")
print(f"Macro  - Precision: {prec_macro:.3f}, Recall: {rec_macro:.3f}, F1: {f1_macro:.3f}")

# Cell 23: Feature importance via coefficients (Sentiment)

feature_names_sent = np.array(tfidf_sent.get_feature_names_out())
coef_sent = log_reg_sentiment.coef_  # shape: (3, n_features)
classes_sent = log_reg_sentiment.classes_

def show_top_features_for_class(coef_row, class_name, top_n=15):
    # top positive coefficients
    top_pos_idx = np.argsort(coef_row)[-top_n:][::-1]
    # top negative coefficients
    top_neg_idx = np.argsort(coef_row)[:top_n]

    print(f"\n=== Top + words for class '{class_name}' ===")
    for idx in top_pos_idx:
        print(f"{feature_names_sent[idx]:<25} {coef_row[idx]:.3f}")

    print(f"\n=== Top - words for class '{class_name}' (push away) ===")
    for idx in top_neg_idx:
        print(f"{feature_names_sent[idx]:<25} {coef_row[idx]:.3f}")

for i, cls in enumerate(classes_sent):
    show_top_features_for_class(coef_sent[i], cls, top_n=15)

# Cell 24: Feature importance via coefficients (Trust)

feature_names_trust = np.array(tfidf_trust.get_feature_names_out())
coef_trust = log_reg_trust.coef_
classes_trust = log_reg_trust.classes_

for i, cls in enumerate(classes_trust):
    print("\n" + "="*60)
    print(f"TRUST CLASS: {cls}")
    show_top_features_for_class(coef_trust[i], cls, top_n=15)

# Cell 25: Install SHAP and LIME for interpretability

!pip install shap lime

# Cell 26: SHAP explanations for 3-class sentiment model

import shap

# SHAP for linear models with sparse inputs
explainer_sent = shap.LinearExplainer(log_reg_sentiment, X_train_tfidf_sent, feature_perturbation="interventional")
# To keep it fast, use a subset of test data
X_test_sample = X_test_tfidf_sent[:300]
shap_values_sent = explainer_sent.shap_values(X_test_sample)

# Global summary plot for one class, e.g., "positive"
feature_names_array = tfidf_sent.get_feature_names_out()

# Convert X_test_sample to a dense array for compatibility with shap.summary_plot
# This addresses potential shape/type mismatches when shap_values are dense
# but features are sparse.
X_test_sample_dense = X_test_sample.toarray()

# This will open a SHAP summary plot in Colab
shap.summary_plot(shap_values_sent[0], X_test_sample_dense, feature_names=feature_names_array, show=True)

# Cell 27: LIME explanation for a single text example (Sentiment)

from lime.lime_text import LimeTextExplainer

class_names_for_lime = list(classes_sent)  # ["negative","neutral_mixed","positive"] or similar order

def predict_proba_for_lime(text_list):
    X_t = tfidf_sent.transform(text_list)
    return log_reg_sentiment.predict_proba(X_t)

explainer_lime = LimeTextExplainer(class_names=class_names_for_lime)

# Pick an example from the test set
i = 0
text_example = X_test_text_sent.iloc[i]
true_label = y_test_sent.iloc[i]

print("TEXT EXAMPLE:")
print(text_example)
print("True sentiment label:", true_label)

exp = explainer_lime.explain_instance(
    text_instance=text_example,
    classifier_fn=predict_proba_for_lime,
    num_features=10
)

# Show explanation inline in Colab
exp.show_in_notebook(text=True)
